### ISSUE TITLE
Why not Ext JS 4.2.3

### ISSUE THREAD

**Issue by rumatoest** [suprojs/extjs-4.2#3]
According to Senhca docs latests version of ExtJs 4 is 4.2.3
Why you are still based on 4.2.2?

**Comment by olecom** [comment]
Due to license issues. Please see https://github.com/suprojs/supro/wiki/ExtJS-4.2.2-patches

**Comment by rumatoest** [comment]
But they are "Sencha Ext JS is made available under Commercial License or the GNU General Public License version 3 (GPLv3)."
http://www.sencha.com/legal/

And you can get GPL version from here
http://www.sencha.com/legal/GPL/

P.S. It is looking like Sencha developers still can not undertand how GPL 3 working.
